name: Cypress TS Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      
    - name: Install cypress
      run: npm install cypress --save-dev
      
    - name: Install allure combine
      run: npm i allure-combined
      
    - name: Install allure commandline
      run: npm i allure-commandline
      
    - name: Run Tests
      run: npx cypress run --env allure=true
      
    - name: Run Tests 2
      run: allure generate allure-results --clean -o allure-report
      env:
        PATH: C:\hostedtoolcache\node\16.3.0\x64\bin:${{ env.PATH }}
      shell: cmd
      
    - name: Generate Sharable Allure HTML Report
      run: allure-combine allure-report --dest Final_Report --auto-create-folders
      
    - name: Upload combined Allure HTML report
      uses: actions/upload-artifact@v2
      with:
          name: Final Allure HTML Report
          path: Final_Report
